import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./shared/navbar/Navbar";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";

const InterSans = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={InterSans.className}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                fontFamily: InterSans.style.fontFamily,
              },
            }}
          >
            <Navbar />
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
